// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4sJ2vGXX7gYKusSMRgY7MiUPYrimF6-M',
    appId: '1:829015770870:web:051d0ea520ffffdbfaced7',
    messagingSenderId: '829015770870',
    projectId: 'dtouchdental-65cea',
    authDomain: 'dtouchdental-65cea.firebaseapp.com',
    databaseURL: 'https://dtouchdental-65cea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dtouchdental-65cea.appspot.com',
    measurementId: 'G-M40J1TXHPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaOlrMD2C04mRY6ZhQ9M9REgiT5N4MwHM',
    appId: '1:829015770870:android:946d23e17a3f7922faced7',
    messagingSenderId: '829015770870',
    projectId: 'dtouchdental-65cea',
    databaseURL: 'https://dtouchdental-65cea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dtouchdental-65cea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIsc8PtrfhwPd4MViwf7ZR5SmqM0YAuN8',
    appId: '1:829015770870:ios:a2ad84d243dfb2fcfaced7',
    messagingSenderId: '829015770870',
    projectId: 'dtouchdental-65cea',
    databaseURL: 'https://dtouchdental-65cea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dtouchdental-65cea.appspot.com',
    iosClientId: '829015770870-iv8qqc4c0dv0a0i3qhq80kal6e5jpcfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtouchdental',
  );
}
